name: Deploy to EC2

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  EC2_IP: ${{ secrets.EC2_IP }}

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ecommerce-products-service .

      - name: Copy Docker Image to EC2
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          docker save ecommerce-products-service:latest | gzip > ecommerce-products-image.tar.gz
          scp -i id_rsa -o StrictHostKeyChecking=no ecommerce-products-image.tar.gz ec2-user@$EC2_IP:~/ecommerce-products-image.tar.gz
          rm id_rsa

      - name: Load and Run Docker Image on EC2
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa -o StrictHostKeyChecking=no ec2-user@$EC2_IP << EOF
            docker load < ~/ecommerce-products-image.tar.gz
            docker run -d -p 3000:3000 ecommerce-products-service:latest
          EOF
          rm id_rsa
